apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-python
    app.kubernetes.io/part-of: e2e-multiple-components
  name: component-python
  namespace: appstudio-e2e-test
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: component-python
status:
  loadBalancer: {}
